version: '3.2'

services:
  web:
    image: portepoisse/task-rest-services-base:latest
    command: "--spring.profiles.active=docker,dockeradmin"
    ports:
      - "8080:8080"
    networks: 
      - net
    volumes:
      - type: bind
        source: ./target/task-rest-services-1.0.0.jar
        target: /app/task-rest-services.jar
    depends_on: 
      - database
  database:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Support2424
      - POSTGRES_DB=TaskRestServices
    networks: 
      - net
    volumes:
      - type: volume
        source: dbdata/
        target: /var/lib/postgresql/data/
      - type: bind
        source: ./bdd/initdb
        target: /docker-entrypoint-initdb.d

networks:
  net:

volumes:
  weblogs:
  dbdata:
