version: '3.2'

services:
  web:
    depends_on: 
      - database
      - webadmin
  webadmin:
    build: ../spring-boot-admin
    ports: 
      - "8081:8081" 
    networks: 
      - net
  databaseadmin:
    image: dpage/pgadmin4:latest
    environment: 
      - PGADMIN_DEFAULT_EMAIL=loic.petit@capgemini.com
      - PGADMIN_DEFAULT_PASSWORD=Support2424
    ports: 
      - "5433:80"
    networks: 
      - net
