version: '3.2'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks: 
      - net
    volumes:
      - type: volume
        source: weblogs/
        target: /app/logs/
    depends_on: 
      - database
  database:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Support2424
      - POSTGRES_DB=TaskRestServices
    networks: 
      - net
    volumes:
      - type: volume
        source: dbdata/
        target: /var/lib/postgresql/data/
      - type: bind
        source: ./bdd/initdb
        target: /docker-entrypoint-initdb.d

networks:
  net:

volumes:
  weblogs:
  dbdata:
