version: '3.2'

services:
  web:
    image: portepoisse/task-rest-services-base:latest
    command: "--spring.profiles.active=docker,dockeradmin"
    ports:
      - "8080:8080"
    networks: 
      net:
      springbootadminnet:
        aliases:
          - task-rest-services
    volumes:
      - type: bind
        source: ../../app/target/task-rest-services-1.0.0.jar
        target: /app/task-rest-services.jar
    depends_on: 
      - database
      - springbootadmin
  database:
    image: portepoisse/task-rest-services-db
    networks: 
      net:
      pgadminnet:
    volumes:
      - type: volume
        source: dbdata/
        target: /var/lib/postgresql/data/

networks:
  net:

volumes:
  logs:
  dbdata:
