version: '3.2'

services:
  web:
    image: portepoisse/task-rest-services:latest
    ports:
      - "8080:8080"
    networks: 
      net:
      springbootadminnet:
        aliases:
          - task-rest-services
    volumes:
      - type: volume
        source: logs/
        target: /app/logs/
    depends_on: 
      - database
      - springbootadmin
  database:
    image: portepoisse/task-rest-services-db
    networks: 
      net:
      pgadminnet:
    volumes:
      - type: volume
        source: dbdata/
        target: /var/lib/postgresql/data/

networks:
  net:

volumes:
  logs:
  dbdata:
