version: '3.2'

services:
  web:
    image: portepoisse/task-rest-services:latest
    ports:
      - "8080:8080"
    networks: 
      net:
      springbootadminnet:
        aliases:
          - task-rest-services
    volumes:
      - type: volume
        source: logs/
        target: /app/logs/
    depends_on: 
      - database
      - springbootadmin
  database:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Support2424
      - POSTGRES_DB=TaskRestServices
    networks: 
      - net
    volumes:
      - type: volume
        source: dbdata/
        target: /var/lib/postgresql/data/
      - type: bind
        source: ../../app/bdd/initdb
        target: /docker-entrypoint-initdb.d

networks:
  net:

volumes:
  logs:
  dbdata:
